# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Probe < Formula
  desc "Universal LLM API Debugger — intercept, inspect, and replay every AI call your app makes."
  homepage "https://github.com/MuhammadHananAsghar/probe"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MuhammadHananAsghar/probe/releases/download/v0.1.1/probe_darwin_amd64.tar.gz"
      sha256 "ee1da6e07bd3eb404ff872a6313f2f2e21690d2ade9f21784345f9ad1e382c12"

      define_method(:install) do
        bin.install "probe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MuhammadHananAsghar/probe/releases/download/v0.1.1/probe_darwin_arm64.tar.gz"
      sha256 "8c5619ab7f020027d558827478565f797ced54786f1aead580c9b97fe2291a04"

      define_method(:install) do
        bin.install "probe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MuhammadHananAsghar/probe/releases/download/v0.1.1/probe_linux_amd64.tar.gz"
      sha256 "6df131f4620eeb2d1a86a655698e2ae1cabf70233ebba5606b22ac37c07088d2"
      define_method(:install) do
        bin.install "probe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MuhammadHananAsghar/probe/releases/download/v0.1.1/probe_linux_arm64.tar.gz"
      sha256 "5a4138da65ca27522b0228060f3bdf2b5ffc59842c808ab151385a01b3445630"
      define_method(:install) do
        bin.install "probe"
      end
    end
  end

  test do
    system "#{bin}/probe", "version"
  end
end
