# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Probe < Formula
  desc "Universal LLM API Debugger — intercept, inspect, and replay every AI call your app makes."
  homepage "https://github.com/MuhammadHananAsghar/probe"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MuhammadHananAsghar/probe/releases/download/v0.1.3/probe_darwin_amd64.tar.gz"
      sha256 "fc186b6912695496ee32a1629f7b7dd44cfedc5755529a512abc6faaf404cbc0"

      define_method(:install) do
        bin.install "probe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MuhammadHananAsghar/probe/releases/download/v0.1.3/probe_darwin_arm64.tar.gz"
      sha256 "7266c8f15e19d963ce1afade720394b0e4250936475ed9db75e71d734f6a67a5"

      define_method(:install) do
        bin.install "probe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MuhammadHananAsghar/probe/releases/download/v0.1.3/probe_linux_amd64.tar.gz"
      sha256 "697f004ba8ae259387d3a0c3db3fd2d5438b01ac450ae9cb25ba4f1ecb73f4b1"
      define_method(:install) do
        bin.install "probe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MuhammadHananAsghar/probe/releases/download/v0.1.3/probe_linux_arm64.tar.gz"
      sha256 "f7fddcabd7a3737d02eaba0ff445bf1ae6980e0d221660f851bb10ec1d9b1530"
      define_method(:install) do
        bin.install "probe"
      end
    end
  end

  test do
    system "#{bin}/probe", "version"
  end
end
