# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wormhole < Formula
  desc "Expose your localhost to the internet. Open-source ngrok alternative."
  homepage "https://github.com/MuhammadHananAsghar/wormhole"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MuhammadHananAsghar/wormhole/releases/download/v0.2.0/wormhole_darwin_amd64.tar.gz"
      sha256 "bee99d91701fe50eed284c1eb1821f002a1de34a38ea79abd7974fda2aa9145a"

      define_method(:install) do
        bin.install "wormhole"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MuhammadHananAsghar/wormhole/releases/download/v0.2.0/wormhole_darwin_arm64.tar.gz"
      sha256 "92875b4a160fc0eab2c69af4a9e1c66fdd0a050be16de8c91b2cf4c7e20cb0dc"

      define_method(:install) do
        bin.install "wormhole"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MuhammadHananAsghar/wormhole/releases/download/v0.2.0/wormhole_linux_amd64.tar.gz"
      sha256 "bf5f22f8834236c48ebf6d907f92e67d1d3cd77b6a5113fd16e6c7e8dbbf258f"
      define_method(:install) do
        bin.install "wormhole"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MuhammadHananAsghar/wormhole/releases/download/v0.2.0/wormhole_linux_arm64.tar.gz"
      sha256 "4bb24fff9bd587858c8c68a9c003b9d2b8ae583b8c33cf93c870a521eeee9718"
      define_method(:install) do
        bin.install "wormhole"
      end
    end
  end

  test do
    system "#{bin}/wormhole", "version"
  end
end
