# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wormhole < Formula
  desc "Expose your localhost to the internet. Open-source ngrok alternative."
  homepage "https://github.com/MuhammadHananAsghar/wormhole"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MuhammadHananAsghar/wormhole/releases/download/v0.1.0/wormhole_darwin_amd64.tar.gz"
      sha256 "54a8d65f8a59bc019930126b52064740b27d0b8fe84e556dd3e1adeae94dc769"

      define_method(:install) do
        bin.install "wormhole"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MuhammadHananAsghar/wormhole/releases/download/v0.1.0/wormhole_darwin_arm64.tar.gz"
      sha256 "aefa500e57677c4bf545c871ad202a5ee1bd87a4ea3e6a208c5f0cdf302f8cde"

      define_method(:install) do
        bin.install "wormhole"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MuhammadHananAsghar/wormhole/releases/download/v0.1.0/wormhole_linux_amd64.tar.gz"
      sha256 "374e172bb3d6bf04f8ba809eff43da604829b10444354d623ae398825faa26de"
      define_method(:install) do
        bin.install "wormhole"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MuhammadHananAsghar/wormhole/releases/download/v0.1.0/wormhole_linux_arm64.tar.gz"
      sha256 "cb66ebbb593bbae4cfee58104ec9e6a31f23b46cd6edfa7f442a0d7c1d138ed2"
      define_method(:install) do
        bin.install "wormhole"
      end
    end
  end

  test do
    system "#{bin}/wormhole", "version"
  end
end
